// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/17/2026, 6:28:23 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/workspaces/videodownloader/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/videodownloader/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/videodownloader/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/videodownloader/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/workspaces/videodownloader/plugins/**/*.{js,ts,mjs}","/workspaces/videodownloader/composables/**/*.{js,ts,mjs}","/workspaces/videodownloader/utils/**/*.{js,ts,mjs}","/workspaces/videodownloader/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/workspaces/videodownloader/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/workspaces/videodownloader/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;